version: "2"

services:

  frontend:
    build: .
    ports:
      - "8083:8080"
    networks:
      - company-mysql
    depends_on:
      - mysql

  mysql:
    image: mysql
    networks:
      - company-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=companyproject
networks:
  company-mysql:
